// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionRequest struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AccountID            string               `protobuf:"bytes,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Amount               int64                `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Currency             string               `protobuf:"bytes,6,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Notes                string               `protobuf:"bytes,7,opt,name=Notes,proto3" json:"Notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TransactionRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *TransactionRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TransactionRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TransactionRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransactionRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *TransactionRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type TransactionReply struct {
	Completed            bool     `protobuf:"varint,1,opt,name=Completed,proto3" json:"Completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReply) Reset()         { *m = TransactionReply{} }
func (m *TransactionReply) String() string { return proto.CompactTextString(m) }
func (*TransactionReply) ProtoMessage()    {}
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *TransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReply.Unmarshal(m, b)
}
func (m *TransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReply.Marshal(b, m, deterministic)
}
func (m *TransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReply.Merge(m, src)
}
func (m *TransactionReply) XXX_Size() int {
	return xxx_messageInfo_TransactionReply.Size(m)
}
func (m *TransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReply proto.InternalMessageInfo

func (m *TransactionReply) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func init() {
	proto.RegisterType((*TransactionRequest)(nil), "transaction.TransactionRequest")
	proto.RegisterType((*TransactionReply)(nil), "transaction.TransactionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	StoreTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
}

type transactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransactionServiceClient(cc *grpc.ClientConn) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) StoreTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/StoreTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	StoreTransaction(context.Context, *TransactionRequest) (*TransactionReply, error)
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_StoreTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).StoreTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/StoreTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).StoreTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreTransaction",
			Handler:    _TransactionService_StoreTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x4e, 0xb3, 0x40,
	0x14, 0xfd, 0xa0, 0x5f, 0xb1, 0x0c, 0x89, 0xa9, 0x13, 0x63, 0x26, 0x44, 0x53, 0xc2, 0x8a, 0x15,
	0x35, 0x75, 0xe3, 0x96, 0xc0, 0x86, 0x8d, 0x0b, 0xca, 0x0b, 0xd0, 0xe9, 0xb5, 0xc1, 0x00, 0x33,
	0x0e, 0x17, 0x13, 0xde, 0xd8, 0xc7, 0x30, 0x0c, 0x56, 0x68, 0x8c, 0xcb, 0xf3, 0x73, 0x39, 0x9c,
	0x33, 0xe4, 0x06, 0x55, 0xd1, 0xb4, 0x05, 0xc7, 0x52, 0x34, 0xa1, 0x54, 0x02, 0x05, 0x75, 0x66,
	0x94, 0xbb, 0x39, 0x09, 0x71, 0xaa, 0x60, 0xab, 0xa5, 0x43, 0xf7, 0xba, 0xc5, 0xb2, 0x86, 0x16,
	0x8b, 0x5a, 0x8e, 0x6e, 0xff, 0xd3, 0x20, 0x34, 0x9f, 0x0e, 0x32, 0x78, 0xef, 0xa0, 0x45, 0x7a,
	0x4d, 0xcc, 0x34, 0x61, 0x86, 0x67, 0x04, 0x8b, 0xcc, 0x4c, 0x13, 0x7a, 0x4f, 0xec, 0x88, 0x73,
	0xd1, 0x35, 0x98, 0x26, 0xcc, 0xf4, 0x8c, 0xc0, 0xce, 0x26, 0x82, 0x3e, 0x13, 0x3b, 0x56, 0x50,
	0x20, 0x1c, 0x23, 0x64, 0x0b, 0xcf, 0x08, 0x9c, 0x9d, 0x1b, 0x8e, 0xc9, 0xe1, 0x39, 0x39, 0xcc,
	0xcf, 0xc9, 0xd9, 0x64, 0xa6, 0x1e, 0x71, 0x12, 0x68, 0xb9, 0x2a, 0xe5, 0x90, 0xce, 0xfe, 0xeb,
	0x2f, 0xcf, 0x29, 0x7a, 0x47, 0xac, 0xa8, 0x1e, 0x72, 0xd8, 0x52, 0xff, 0xcd, 0x37, 0xa2, 0x2e,
	0x59, 0xc5, 0x9d, 0x52, 0xd0, 0xf0, 0x9e, 0x59, 0xfa, 0xec, 0x07, 0xd3, 0x5b, 0xb2, 0x7c, 0x11,
	0x08, 0x2d, 0xbb, 0xd2, 0xc2, 0x08, 0xfc, 0x47, 0xb2, 0xbe, 0x68, 0x2a, 0xab, 0x7e, 0xe8, 0x15,
	0x8b, 0x5a, 0x56, 0x80, 0x70, 0xd4, 0x75, 0x57, 0xd9, 0x44, 0xec, 0xde, 0x2e, 0xb6, 0xd9, 0x83,
	0xfa, 0x28, 0x39, 0xd0, 0x9c, 0xac, 0xf7, 0x28, 0x14, 0xcc, 0x24, 0xba, 0x09, 0xe7, 0x0f, 0xf1,
	0x7b, 0x50, 0xf7, 0xe1, 0x6f, 0x83, 0xac, 0x7a, 0xff, 0xdf, 0xc1, 0xd2, 0x43, 0x3d, 0x7d, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x07, 0xc4, 0xf0, 0x15, 0xd2, 0x01, 0x00, 0x00,
}
